[vars]

[vars.app]
name = "rusible"
env = "dev"
role = "base"

[vars.group]
primary = "web"

[[groups]]
name = "prod"
children = ["web", "db"]

[[groups]]
name = "ops"
children = ["monitoring"]

[[groups]]
name = "web"

[[groups]]
name = "db"

[[groups]]
name = "monitoring"

[[hosts]]
name = "web-1"
host = "127.0.0.1"
port = 2222
user = "root"
password = "123456"
vars = { app = { role = "frontend" } }
groups = ["web"]

[[hosts]]
name = "db-1"
host = "127.0.0.1"
port = 2223
user = "root"
password = "123456"
vars = { app = { role = "database" }, group = { primary = "db" } }
groups = ["db"]

[[hosts]]
name = "ops-1"
host = "127.0.0.1"
port = 2224
user = "root"
password = "123456"
vars = { app = { role = "monitoring" }, group = { primary = "ops" } }
groups = ["web", "monitoring"]
