[package]
name = "rusible"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "[WIP] Writing infrastructure automation tasks in Rust."
readme = "README.md"

[dependencies]
russh = { workspace = true }
russh-sftp = { workspace = true }
rusible-meta = { workspace = true }
rusible-template = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "process", "rt"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-forest = { workspace = true }
tracing-subscriber = { workspace = true }
