[package]
name = "rusible-exec"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Task executor binary for applying Rusible tasks on a target host."
readme = "README.md"

[dependencies]
clap = { workspace = true }
minijinja = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls"] }
rusible-meta = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-std", "io-util", "macros", "net", "process", "rt", "time"] }
toml = { workspace = true }
